[package]
name = "webcam_streamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-channel = "2.3.1"
byte-slice-cast = "1.2.2"
chrono = "0.4.38"
env_logger = "0.11.5"
futures-util = "0.3.30"
gstreamer = "0.23.0"
gstreamer-app = "0.23.0"
log = "0.4.22"
poem = { version = "3.1.0", features = ["static-files", "websocket"] }
poem-openapi = "5.1.2"
termion = "4.0.2"
tokio = { version = "1.40.0", features = ["full"] }
