[package]
name = "webcam_streamer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
futures-util = "0.3.30"
gstreamer = { version="0.23.0", default-features = false, features = [] }
gstreamer-app = { version="0.23.0", default-features = false, features = [] }
poem = { version = "3.1.0", features = ["static-files", "websocket"] }
poem-openapi = "5.1.2"
tokio = { version = "1.40.0", features = ["full"] }
v4l = "0.14.0"
